CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    TITLE VARCHAR(255),
    DESCRIPTION TEXT,
    BRAND_ID VARCHAR(255),
    SALE_PRICE DECIMAL(10, 2),
    QUANTITY INTEGER,
    DISCOUNT DECIMAL(10, 2),
    TYPE VARCHAR(255)
    );